[tool.poetry]
name = "gdmc"
version = "0.1.0"
description = ""
authors = ["AlexisMoins <moinsalexis@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
gdpc = "^5.0.2"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
